# -*- coding: utf-8 -*-
"""one more.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alFc5OOQAkPptWkLRev4dywyRHYQay4i
"""

pip install requests

pip install schedule sqlalchemy

import os
import sys
import time
import logging
import requests
import pandas as pd
import schedule
from datetime import datetime
from sqlalchemy import create_engine, text

API_KEY        = "YOUR_API_KEY"           # <-- replace this
MASTER_CSV     = "tamil_nadu_walkins_master.csv"
DB_PATH        = "jobs.db"
RUN_INTERVAL_H = 6                             # how often to refresh (hours)

DISTRICTS = [ "Chennai",
    "Coimbatore",
    "Salem",
    "Madurai",
    "Tiruchirapalli",
    "Erode",
    "Tirunelveli",
    "Vellore"]

SEARCH_QUERIES = [
    "walk-in drive IN {district} Tamil Nadu",
    "walkin {district} India",
]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

def fetch_jobs_for_district(district: str) -> list[dict]:
    """Fetch walk-in jobs for one district using multiple query variants."""
    all_jobs = []
    headers = {
        "X-RapidAPI-Key":  API_KEY,
        "X-RapidAPI-Host": "jsearch.p.rapidapi.com",
    }

    for query_template in SEARCH_QUERIES:
        query = query_template.format(district=district)
        for page in range(1, 3):   # 2 pages = ~20 results per query
            try:
                response = requests.get(
                    "https://jsearch.p.rapidapi.com/search",
                    headers=headers,
                    params={
                        "query":            query,
                        "page":             page,
                        "num_pages":        1,
                        "country":          "in",
                        "language":         "en",
                        "date_posted":      "week",
                        "employment_types": "FULLTIME,PARTTIME",
                        "radius":           50,
                    },
                    timeout=60,
                )
                response.raise_for_status()
                data = response.json().get("data", [])
                all_jobs.extend(data)
                log.info(f"  {district} | '{query}' page {page} → {len(data)} jobs")
                time.sleep(0.5)   # gentle rate limiting

            except requests.exceptions.HTTPError as e:
                log.warning(f"  HTTP error for {district}: {e}")
            except requests.exceptions.RequestException as e:
                log.warning(f"  Request failed for {district}: {e}")

    return all_jobs

def inr_to_lpa(value) -> float | None:
    """Convert raw salary value to LPA (lakhs per annum)."""
    if value is None:
        return None
    try:
        v = float(value)
        if v > 100000:          # stored in INR
            return round(v / 100000, 2)
        return round(v, 2)      # already in LPA
    except (ValueError, TypeError):
        return None

def clean_jobs(raw_jobs: list[dict], district: str) -> pd.DataFrame:
    """Extract relevant fields, fix types, add derived columns."""
    rows = []
    today = datetime.now().strftime("%Y-%m-%d")

    for job in raw_jobs:
        min_sal = inr_to_lpa(job.get("job_min_salary"))
        max_sal = inr_to_lpa(job.get("job_max_salary"))

        # fix: proper parentheses around each or-expression before dividing
        if min_sal is not None and max_sal is not None:
            ctc_avg = round((min_sal + max_sal) / 2, 2)
        elif min_sal is not None:
            ctc_avg = min_sal
        elif max_sal is not None:
            ctc_avg = max_sal
        else:
            ctc_avg = None

        rows.append({
            "Fetch_Date":       today,
            "District":         district,
            "Company":          job.get("employer_name"),
            "Job_Title":        job.get("job_title"),
            "Employment_Type":  job.get("job_employment_type"),
            "CTC_Min_LPA":      min_sal,
            "CTC_Max_LPA":      max_sal,
            "CTC_Avg_LPA":      ctc_avg,
            "CTC_Min_INR":      job.get("job_min_salary"),
            "CTC_Max_INR":      job.get("job_max_salary"),
            "Salary_Period":    job.get("job_salary_period"),
            "Location":         job.get("job_location"),
            "City":             job.get("job_city"),
            "Country":          job.get("job_country"),
            "Location_Type":    job.get("work_arrangement", "Onsite"),
            "Remote":           job.get("job_is_remote", False),
            "Posted_Date":      job.get("job_posted_at_datetime_utc"),
            "Apply_URL":        job.get("job_apply_link"),
            "Employer_Logo":    job.get("employer_logo"),
            "Job_ID":           job.get("job_id"),
        })

    df = pd.DataFrame(rows)
    if df.empty:
        return df

    # parse dates
    df["Posted_Date"] = pd.to_datetime(df["Posted_Date"], errors="coerce")
    df["Fetch_Date"]  = pd.to_datetime(df["Fetch_Date"],  errors="coerce")

    # normalise employment type
    df["Employment_Type"] = df["Employment_Type"].str.upper().str.strip()

    # drop duplicates by Job_ID
    df = df.drop_duplicates(subset="Job_ID", keep="first")

    return df

def save_to_csv(df: pd.DataFrame):
    """Append to master CSV and write today's daily snapshot."""
    date_str   = datetime.now().strftime("%Y-%m-%d")
    daily_csv  = f"tamil_nadu_walkins_{date_str}.csv"

    # daily snapshot (overwrite)
    df.to_csv(daily_csv, index=False)
    log.info(f"Daily snapshot saved → {daily_csv}")

    # master: load existing, append, deduplicate
    if os.path.exists(MASTER_CSV):
        master = pd.read_csv(MASTER_CSV)
        master["Posted_Date"] = pd.to_datetime(master["Posted_Date"], errors="coerce")
        master["Fetch_Date"]  = pd.to_datetime(master["Fetch_Date"],  errors="coerce")
        combined = pd.concat([master, df], ignore_index=True)
    else:
        combined = df

    combined = combined.drop_duplicates(subset="Job_ID", keep="last")
    combined.to_csv(MASTER_CSV, index=False)
    log.info(f"Master CSV updated → {MASTER_CSV}  ({len(combined)} total records)")

def save_to_sqlite(df: pd.DataFrame):
    """Append new records to SQLite, deduplicate by Job_ID."""
    engine = create_engine(f"sqlite:///{DB_PATH}")
    df.to_sql("jobs", engine, if_exists="append", index=False)

    with engine.connect() as con:
        con.execute(text("""
            DELETE FROM jobs
            WHERE rowid NOT IN (
                SELECT MIN(rowid) FROM jobs GROUP BY Job_ID
            )
        """))
        con.commit()
        count = con.execute(text("SELECT COUNT(*) FROM jobs")).scalar()
    log.info(f"SQLite updated → {DB_PATH}  ({count} total records)")

def print_summary(df: pd.DataFrame):
    """Print a district-level summary table to the console."""
    if df.empty:
        log.warning("No data fetched — check your API key and quota.")
        return

    print("\n" + "="*60)
    print("TAMIL NADU WALK-IN SUMMARY  |  " + datetime.now().strftime("%Y-%m-%d %H:%M"))
    print("="*60)

    summary = (
        df.groupby("District")
        .agg(
            Total_Jobs      = ("Job_ID",          "count"),
            Avg_CTC_LPA     = ("CTC_Avg_LPA",     "mean"),
            Remote_Jobs     = ("Remote",           "sum"),
            Fulltime_Jobs   = ("Employment_Type",  lambda x: (x == "FULLTIME").sum()),
            Parttime_Jobs   = ("Employment_Type",  lambda x: (x == "PARTTIME").sum()),
        )
        .reset_index()
    )
    summary["Avg_CTC_LPA"] = summary["Avg_CTC_LPA"].round(2)
    print(summary.to_string(index=False))

    print("\nTop 10 hiring companies:")
    top_cos = (
        df.groupby("Company")["Job_ID"]
        .count()
        .sort_values(ascending=False)
        .head(10)
        .reset_index()
        .rename(columns={"Job_ID": "Jobs"})
    )
    print(top_cos.to_string(index=False))
    print("="*60 + "\n")

def run_pipeline():
    log.info("Pipeline started")
    all_frames = []

    for district in DISTRICTS:
        log.info(f"Fetching → {district}")
        raw = fetch_jobs_for_district(district)
        df  = clean_jobs(raw, district)
        if not df.empty:
            all_frames.append(df)
        time.sleep(1)   # pause between districts

    if not all_frames:
        log.warning("Pipeline finished with 0 records.")
        return

    combined = pd.concat(all_frames, ignore_index=True)
    combined = combined.drop_duplicates(subset="Job_ID", keep="first")

    save_to_csv(combined)
    save_to_sqlite(combined)
    print_summary(combined)
    log.info("Pipeline finished successfully.")

if __name__ == "__main__":
    if API_KEY == "YOUR_API_KEY":
        print("ERROR: Please set your API_KEY at the top of this file.")
        print("  Get one free at: https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch")
        sys.exit(1)

    if "--run-once" in sys.argv:
        run_pipeline()
    else:
        log.info(f"Scheduler started — pipeline runs every {RUN_INTERVAL_H} hours.")
        log.info("Press Ctrl+C to stop. Run with --run-once for a single execution.")
        run_pipeline()                                  # run immediately on start
        schedule.every(RUN_INTERVAL_H).hours.do(run_pipeline)
        while True:
            schedule.run_pending()
            time.sleep(60)

from google.colab import files

files.download("tamil_nadu_walkins_master.csv")

import requests
import pandas as pd
from datetime import datetime
import os

APP_ID  = "YOUR_ADZUNA_APP_ID"
APP_KEY = "YOUR_ADZUNA_API_KEY"

districts = ["Chennai", "Coimbatore", "Salem", "Madurai",
             "Tiruchirapalli", "Erode", "Tirunelveli", "Vellore"]

all_jobs = []

for district in districts:
    print(f"Fetching {district}...")

    try:
        res = requests.get(
            f"https://api.adzuna.com/v1/api/jobs/in/search/1",
            params={
                "app_id":           APP_ID,
                "app_key":          APP_KEY,
                "what":             "walk in ",
                "where":            f"{district}, Tamil Nadu",
                "results_per_page": 50,
                "distance": 30,
            },
            timeout=15
        )

        jobs = res.json().get("results", [])
        print(f"✅ {district}: {len(jobs)} jobs found")

        for job in jobs:
            sal_min = job.get("salary_min", 0) or 0
            sal_max = job.get("salary_max", 0) or 0

            all_jobs.append({
                "Date":        datetime.now().strftime("%Y-%m-%d"),
                "District":    district,
                "Company":     job.get("company", {}).get("display_name", ""),
                "Job_Title":   job.get("title", ""),
                "Location":    job.get("location", {}).get("display_name", ""),
                "CTC_Min_LPA": round(sal_min / 100000, 2) if sal_min > 1000 else sal_min,
                "CTC_Max_LPA": round(sal_max / 100000, 2) if sal_max > 1000 else sal_max,
                "CTC_Avg_LPA": round(((sal_min + sal_max) / 2) / 100000, 2) if sal_min > 1000 else 0,
                "Posted_Date": job.get("created", ""),
                "Apply_URL":   job.get("redirect_url", ""),
            })

    except Exception as e:
        print(f"❌ {district} error: {e}")

print(f"\n✅ Total jobs fetched: {len(all_jobs)}")

if all_jobs:
    new_df = pd.DataFrame(all_jobs)

    # பழைய CSV இருந்தா அதோட சேர்
    if os.path.exists("tamil_nadu_walkins_master.csv"):
        old_df = pd.read_csv("tamil_nadu_walkins_master.csv")
        combined = pd.concat([old_df, new_df], ignore_index=True)
        combined = combined.drop_duplicates(subset=["Job_Title","Company","District"], keep="last")
    else:
        combined = new_df

    combined.to_csv("tamil_nadu_walkins_master.csv", index=False)
    print(f"✅ CSV saved! Total records: {len(combined)}")
    print(combined[["District","Company","Job_Title","CTC_Min_LPA"]].head(15))
else:
    print("❌ No jobs found - check your App ID and API Key")

!pip install office365-rest-python-client -q

from google.colab import files
files.download("tamil_nadu_walkins_master.csv")

!pip install requests pandas -q

import requests
import pandas as pd
from datetime import datetime

APP_ID  = "YOUR_ADZUNA_APP_ID"
APP_KEY = "YOUR_ADZUNA_API_KEY"

districts = ["Chennai", "Coimbatore", "Salem", "Madurai",
             "Tiruchirapalli", "Erode", "Tirunelveli", "Vellore"]

all_jobs = []

for district in districts:
    print(f"Fetching {district}...")
    try:
        res = requests.get(
            "https://api.adzuna.com/v1/api/jobs/in/search/1",
            params={
                "app_id": APP_ID,
                "app_key": APP_KEY,
                "what": "walk in",
                "where": f"{district}, Tamil Nadu",
                "results_per_page": 50,
                "distance": 30,
            },
            timeout=15
        )
        jobs = res.json().get("results", [])
        print(f"✅ {district}: {len(jobs)} jobs found")

        for job in jobs:
            sal_min = job.get("salary_min", 0) or 0
            sal_max = job.get("salary_max", 0) or 0
            all_jobs.append({
                "Fetch_Date":      datetime.now().strftime("%Y-%m-%d"),
                "District":        district,
                "Company":         job.get("company", {}).get("display_name", ""),
                "Job_Title":       job.get("title", ""),
                "Location":        job.get("location", {}).get("display_name", ""),
                "CTC_Min_LPA":     round(sal_min / 100000, 2) if sal_min > 1000 else 0,
                "CTC_Max_LPA":     round(sal_max / 100000, 2) if sal_max > 1000 else 0,
                "Posted_Date":     job.get("created", ""),
                "Apply_URL":       job.get("redirect_url", ""),
                "INTERVIEW_MODE":  "Walk-In"
            })
    except Exception as e:
        print(f"❌ {district} error: {e}")

print(f"\n✅ Total jobs fetched: {len(all_jobs)}")

df = pd.DataFrame(all_jobs)
df = df.drop_duplicates(subset=["Job_Title","Company","District"], keep="last")
df.to_csv("tamil_nadu_walkins_master.csv", index=False)
print(f"✅ CSV saved! Total records: {len(df)}")
print(df[["District","Company","Job_Title"]].head(10))

from google.colab import files
files.download("tamil_nadu_walkins_master.csv")